### ISSUE TITLE
GridView triangles

### ISSUE THREAD

**Issue by johnty** [libmapper/webmapper#12]
A few minor issues with the triangles that represent an intersection (map) on the grid:

1. Initially when opening the view, they are often the wrong size (much larger than the grid).

2. When the view is resized, they get back to close to the right size (but are still slightly larger than the box they should reside in).

3. When scrolling the view, map triangles that move beyond the left border (output sig list) are drawn above the list. Perhaps they should be drawn underneath the sig table, or hidden completely?

**Comment by malloch** [comment]
I believe the first issue is due to a zoom miscalculation in SignalTable – it also affects other views containing tables.

**Comment by malloch** [comment]
1. avoided by resetting zoom & scroll when view changed (commit 7ff3e42)
2. paths resized in commit 7ff3e42
3. addressed by adjusting the position and dimensions of the div containing our svg canvas (commits da99f9a and d72099c)
