### ISSUE TITLE
Expression syntax link dead

### ISSUE THREAD

**Issue by jcelerier** [libmapper/webmapper#22]
Hello !
In this repo's README, there's a reference to the expression syntax documentation, but it seems that the link it points to is dead (https://github.com/libmapper/webmapper/blob/main/doc/expression_syntax.html).

I've tried looking for it but didn't find it.
Is it somewhere online ? Thanks !

**Comment by johnty** [comment]
[Here's the link](https://github.com/libmapper/libmapper/blob/main/doc/expression_syntax.md), we can updated it if @malloch can verify if the doc is the most up to date.

**Comment by malloch** [comment]
Fixed in commit bbde042
Thanks!
