### ISSUE TITLE
Webmapper refuses to switch network interface via GUI

### ISSUE THREAD

**Issue by aburt2** [libmapper/webmapper#39]
When trying to select an interface in the browser for webmapper it refreshes and either closes the connection completely or opens the old interface,

I've tried using the iface flag as well (with no success) but I'm not entirely sure how windows actually names their interfaces. No error messages show up in the terminal

Browser: Microsoft Edge
Platform: Windows 10 22H2

Video showing issue (same problem occurs when switching to Wi-Fi interface as well):
https://github.com/libmapper/webmapper/assets/32888184/5ba70ab2-63ab-4a69-bed4-404dbde49679

**Comment by malloch** [comment]
Hi @aburt2 this is really a libmapper issue since network interface selection wasn't working on Windows. If you have time to do some testing you can checkout the windows_iface_pref branches to libmapper and webmapper:
https://github.com/malloch/libmapper/tree/windows_iface_pref
https://github.com/malloch/webmapper/tree/windows_iface_pref

**Comment by aburt2** [comment]
I will have a look when I have time (hopefully this week), will I have to build the windows_iface_pref branch of libmapper from source?

**Comment by aburt2** [comment]
@malloch I've tested switching network interfaces with the verison of libmapper and webmapper on your branch, there is a small error that stops it from running on line 374 of webmapper.py

https://github.com/malloch/webmapper/blob/16f693f3756fa345a250a4f6c1b169ee8f5a7a8e/webmapper.py#L374 

Should be

```
ifaceName = win32_get_name_from_guid(i)
```

It still occasionally crashes when switching interfaces (with no error), but when it does work the interface does change

**Comment by malloch** [comment]
That's progress :)   

I'll merge the branch and close this PR. We can open a new one for "crashes ocassionally on windows when switching network interfaces"
