### ISSUE TITLE
Maps from a table to itself grow in size without bound

### ISSUE THREAD

**Issue by DocSunset** [libmapper/webmapper#9]
Maps from a table to itself (js/views/View.js: MapPath.sameTable), such as output-to-output maps in list view, have their width/radius (ctlx) calculated based on the vertical distance between rows. This value can get unreasonably large. For example, in list view when the rows are very far apart, the arc of the map starts to overlap with arcs on the opposite table, then with the opposite table itself. If the table with the maps is zoomed too much, the arc of the maps starts to go right off the side of the viewport. See screen captures.

I had offered a (somewhat messy) solution to this problem (which may have been a bug in grid view) by constraining the control point offset to some maximum, but as of [this commit](https://github.com/libmapper/webmapper/commit/8e1c375365b8500a0a37fb55701dbf770b2d5d04) it was overwritten. 

I like the way the arcs are all sort of concentric and have the same overall shape, but it would be good if they didn't extend further than e.g. half of the width of the space between tables in list view (i.e. the mapPane.width).

![screen shot 2019-02-15 at 1 32 22 pm](https://user-images.githubusercontent.com/17572588/52878237-245d6a00-312a-11e9-8ff0-7672e2538c78.png)
![screen shot 2019-02-15 at 1 32 33 pm](https://user-images.githubusercontent.com/17572588/52878238-245d6a00-312a-11e9-9331-7e1ec32d76cf.png)

**Comment by malloch** [comment]
Hi Travis,

Sorry for overwriting your changes – in fact the beziers were buggy in all of the table views, since input->input maps would be drawn on top of the right table in list view.

I agree with you about constraining the control points.

best,
Joe

**Comment by radarsat1** [comment]
Heheh neat.
Maybe some force-based algorithm would do a better job?
I have a feeling that directly computing an optimal solution that includes
constraints may be impossible, probably better to cast it as an objective
that includes soft constraints. (ie springs between the lines to enforce
distance and angular springs at the nodes that encourage roundness, smth
like that)

Steve
